### ISSUE TITLE
Js-packages NPM packs

### ISSUE THREAD

**Issue by vivitlair1** [ngdanghau/fontawesome-pro#5]
Hi sir,

Can you include the js-packages that you can download with npm:
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

Looks like that:
https://github.com/FortAwesome/Font-Awesome/tree/master/js-packages/%40fortawesome

Thanks

**Comment by ngdanghau** [comment]
Sorry, because in the source that I have also don't include js-packages, so can't help you.  You can try rewrite in NPM packages with fontawesome-pro.
